version: '3.0'
services:
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./www:/var/www
    links:
      - mysql
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:5-fpm
    volumes:
      - ./code:/code
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=laraveltest"
    ports:
      - "3306:3306"
