version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/web/symfony

  php:
    image: php:7.2.5-fpm-alpine3.7
    ports:
      - 9000:9000
    volumes:
      - .:/web/symfony

volumes:
  symfony:
