version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - type: volume
        source: symfony
        target: /web/symfony
        volume:
          nocopy: true

volumes:
  symfony:
